### ISSUE TITLE
Doesn't work in google meet website.

### ISSUE THREAD

**Issue by Shashank-Salian** [brian-girko/always-active#11]
This extension doesn't work in meet.google.com website. Google meet displays the request join dialogue only when the visibilityState is not "hidden" and this extension was not able to bypass this website. Please find a fix for this.

**Comment by xcasxcursex** [comment]
Try adding this to your policy: 

```
,
  "meet.google.com": [
    "visibility"
  ]
```

**Comment by brian-girko** [comment]
I tried to figure out how Google Meet detects the visibility state but couldn't find anything. If anybody can help, let me know

**Comment by brian-girko** [comment]
Should be fixed by 0.1.9 release.
