### ISSUE TITLE
[Request] Document .isActive

### ISSUE THREAD

**Issue by LillyCosmo** [brian-girko/always-active#14]
Hello,

It seems this doesn't block .isActive states, as tested here:
https://jsbin.com/puhelonuco/edit?html,js,output

Please allow changing it to active

**Comment by xcasxcursex** [comment]
Your script returns an 'inactive' string, when the window.isActive property is not equal to the string, 'active'. The .isActive property is not defined, so your script says the property is defined as 'inactive'. I think this might be a bug in your test script.

Is .inActive in any web spec? I don't think it is.
