### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by AndnixSH** [brian-girko/always-active#15]
This extension is using high CPU usage around 20-30%. As soon as I switched off this extension, the usage went back down

I was trying to debug even though I don't have knowledge in extension, and I caught this error

![image](https://user-images.githubusercontent.com/40742924/147383696-557a3788-5620-4d9b-84ae-a2799a982fcc.png)

Maybe this is the fault?

I used v3 - v0.2.2

**Comment by brian-girko** [comment]
v

**Comment by brian-girko** [comment]
Since I cannot reproduce this, please wait for the 0.2.3 release and report back if you still see the high CPU usage.

**Comment by AndnixSH** [comment]
Ok, i'll wait.

I found a way to reproduce the bug. Have your extension installed with your tabs open and close one of them, it will trigger the bug without any exceptions. If nothing happens, install the extension and close one of your tabs

![image](https://user-images.githubusercontent.com/40742924/147387796-b029d3b3-6e45-4a4a-9d6b-90f36d7e3a20.png)

**Comment by AndnixSH** [comment]
I saw you have commited 0.2.3. I have installed it as unpacked, and it seems to have solved the bug.

**Comment by brian-girko** [comment]
Perfect! v0.2.3 is also released on WebStore. Please reopen if you observed the behavior.
