### ISSUE TITLE
v0.2.4 Twitch "NaN"

### ISSUE THREAD

**Issue by zefie** [brian-girko/always-active#20]
Ever since updating to v0.2.4, Twitch now has issues with displaying Channel Points and View Count, often showing "NaN". 
If you go to a Twitch stream with the extension active, at first everything will appear fine, but then when it tries to do a live update of the numbers, it seems to be a 75/25 (in favor of error) chance of showing "NaN" instead of the actual number.

I have not had this issue with v0.2.3, and I have confirmed this is linked to this extension, because it stops happening if I disable this extension. I could not find anything useful in the devtools error log.

Is there a way I can downgrade back to v0.2.3, or do you have any idea what changes in v0.2.4 would have caused this?  I haven't changed any of the extension's settings since the update.

Thanks, and sorry to bother about this again.

**Comment by brian-girko** [comment]
Can you share a screenshot? I am not sure where to look for that "NaN".

**Comment by zefie** [comment]
In some form of irony, I have figured out that it is triggered when Twitch does the live update, and the tab is not currently active. If you are actively watching the stream or have the tab open, it does not appear to go "NaN", but typing this in a new tab I was able to get the NaN back with the extension active.

![image](https://user-images.githubusercontent.com/612177/158007095-2276810f-6602-4685-8281-1859850f24d5.png)

**Comment by brian-girko** [comment]
I think I found the problem. But since I am still not able to reproduce this, please follow these steps to confirm the fix:

1. Open "chrome://extensions" in a browser tab and disable the extension
2. Turn the developer mode on
3. Download https://github.com/brian-girko/always-active/archive/refs/heads/master.zip and extract it into a local directory.
4. Drop the "v2" directory (src -> v2) to the "chrome://extensions" page.

**Comment by zefie** [comment]
So far so good. I have tested the 0.2.5 test with a stream in another tab for about 15 minutes (in comparison, it only took about 5-6 minutes to reproduce it on 0.2.4 and make that screenshot).

Thanks!
