### ISSUE TITLE
Youtube can detect user activity

### ISSUE THREAD

**Issue by xcasxcursex** [brian-girko/always-active#22]
I noticed this while playing a video in the background. Normally, when the video ends, cards are shown to recommend other videos. 

When the video plays while tab is in the background, the video ends, but the page waits until the tab is foreground again before showing those cards. It can clearly detect that the tab is not visible and when it became visible again.

Happy to help with this if there's anything I can do!

**Comment by Dibbyo456** [comment]
Can confirm. YT can detect.

**Comment by xcasxcursex** [comment]
Closed with 0.2.6 / https://github.com/brian-girko/always-active/commit/84142b9315620f73b14b4b90bf5d065834af3172
