### ISSUE TITLE
Focus event not getting blocked

### ISSUE THREAD

**Issue by zer0-memory** [brian-girko/always-active#27]
This site detects the focus event: [http://www2.stat.duke.edu/~cc248/jsphylosvg/js/yui/tests/event/tests/manual/window-focus-test.html](http://www2.stat.duke.edu/~cc248/jsphylosvg/js/yui/tests/event/tests/manual/window-focus-test.html)

**Comment by brian-girko** [comment]
Thanks for the report. The extension now allows only one focus event to get dispatched.
