### ISSUE TITLE
Enable on all websites by default

### ISSUE THREAD

**Issue by supsm** [brian-girko/always-active#38]
After the recent update, it seems that the extension is off by default unless the user explicitly lists which websites it should be enabled on. IMO, the extension would be most useful if it was "always active" unless disabled via a blacklist. It seems that there is currently no way to restore the original functionality where the extension is enabled on all websites. I have tried using wildcards to no avail.

**Comment by brian-girko** [comment]
I'll add support for "*" from the next release. Still, I recommend enabling the extension on hostnames that need the active tab to function properly.
