### ISSUE TITLE
Type error for parameter scripts (Error processing 0: Unexpected property "matchOriginAsFallback") for scripting.registerContentScripts. 

### ISSUE THREAD

**Issue by trendyan** [brian-girko/always-active#41]
List of Hostnames
*
Save Options
Type error for parameter scripts (Error processing 0: Unexpected property "matchOriginAsFallback") for scripting.registerContentScripts. 

Firefox 115.14.0esr (64 bit)
Always active Window - Always Visible 0.4.3

**Comment by brian-girko** [comment]
Right, I should have set the min version to 128.0
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript

Either update your Firefox or use an older version of the extension. Thanks for the report.
