### ISSUE TITLE
Wildcard or all sub-domains matched functionality

### ISSUE THREAD

**Issue by Saxayone** [brian-girko/always-active#44]
I was wondering if there could be an option to implement some method of matching all sub-domains on a specific site either through wildcard matching or such?

Currently having issues with a couple of websites where they randomize sub-domains and this addon requires every single one to be added every time which is quite frustrating to deal with.

**Comment by brian-girko** [comment]
Have you tried adding the domain name instead of subs? `example.com` matches both `example.com` and `www.example.com`

**Comment by Saxayone** [comment]
Yes, I have tried multiple times and it has never worked for me which is why I made this issue.
I have found that `example.com` will only ever match `example.com` and never `subdomain.example.com`
Using Firefox with addon version 0.4.3
