### ISSUE TITLE
[LINUX] Not working on Version 88.0.4324.96 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by darkRaspberry** [brian-girko/always-active#6]
If there is a system how to collect logs. I can send you.
I'm using Ubuntu chrome.

**Comment by brian-girko** [comment]
Can you share the page with the issue?

**Comment by darkRaspberry** [comment]
its my college exam page [weebox](https://wheebox.com/). what u need the whole html dumb>?

**Comment by zuihook** [comment]
@darkRaspberry 

Bro its working on Proctor Website or not??

**Comment by darkRaspberry** [comment]
@zuihook In Linux in some proctor website doesn't work.
I tested in weebox and it doesn't work for me.

**Comment by zuihook** [comment]
@darkRaspberry Thanks for reply. I will try it in next exam. I missed to use this extensions in Mock Test.
